### ISSUE TITLE
Unable to install new Phreeqc version 3.8.5-17052-x64.msi 

### ISSUE THREAD

**Issue by Samritlm** [usgs-coupled/phreeqc3#86]
Hi,
I previously used Phreeqc 3.7.3. Now I am trying to install a latest version of Phreeqc 3.8.5-17052-x64.msi to my computer- Microsoft Window 10 with 64-bit operating system, without success. The program information are found, but no phreeqc application both in C-drive (where I stored it) and in the start menu (no Phreeqc blue-logo there). Could you please help what could be the problem? Thank you.
Best regards,
![ProblemwithPhreeqc3_8_5](https://github.com/user-attachments/assets/60df2636-e9e7-41f8-91c9-b534e19ea380)

Samrit

**Comment by scharlton2** [comment]
Hi @Samritlm,

Could you be mixing up the phreeqc batch version (which is this repository) with the phreeqc interactive (which is located [here](https://github.com/usgs-coupled/phreeqci))?  Or possibly with Dr C.A.J. Appelo's version located [here](https://www.hydrochemistry.eu/ph3/index.html)?

Scott

**Comment by Samritlm** [comment]
Hi Scott,
Thank you very much for your info and the links. I followed the link you gave and it seems to be ok now (figure a).
I previously downloaded from the link as shown in the figure b) and I didn't notice that it was a batch version.
Best regards,
![Phreeqc_latestversion](https://github.com/user-attachments/assets/2daea016-3a49-4f54-95cb-69e880928335)

Samrit
